[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "pyorbit-package"
version = "12.0.0b0"
description = "PyORBIT: a code for exoplanet orbital parameters and stellar activity"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Luca Malavolta", email = "luca.malavolta@unipd.it" },
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "numpy==1.24.3",
    "numba>=0.55.2",
    "scipy>=1.8.1,<1.12.0",
    "matplotlib>=3.5.2,<3.8",
    "astropy>=5.1",
    "astroquery>=0.4",
    "pyerfa>=2.0",
    "argparse",
    "emcee>=3.1.2",
    "pyyaml",
    "h5py",
    "tqdm",
    "pygtc",
    "jaxlib==0.4.31",
    "jax==0.4.31",
    "tinygp>=0.3.0",
    "ordered-set",
    "packaging",
]

[project.urls]
Homepage = "https://github.com/LucaMalavolta/PyORBIT"

[project.scripts]
pyorbit_run = "pyorbit.pyorbit_run:pyorbit_run"
pyorbit_results = "pyorbit.pyorbit_results:pyorbit_results"

[tool.setuptools]
packages = [
    "pyorbit",
    "pyorbit.common",
    "pyorbit.classes",
    "pyorbit.models",
    "pyorbit.samplers",
    "pyorbit.subroutines",
]
zip-safe = false
